# Generated by Django 2.2.5 on 2019-10-11 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentNumber', models.IntegerField()),
                ('documentType', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('lastName', models.CharField(max_length=63)),
                ('age', models.IntegerField()),
                ('nickname', models.CharField(max_length=31)),
                ('password', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=2)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Owner')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Role')),
            ],
        ),
    ]
