# Generated by Django 2.2.5 on 2019-10-24 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='people',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='people',
            name='name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='people',
            name='password',
        ),
        migrations.RemoveField(
            model_name='people',
            name='token',
        ),
        migrations.AddField(
            model_name='people',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
