# Generated by Django 2.2.5 on 2019-10-20 02:43

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='people',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='people',
            name='id',
        ),
        migrations.RemoveField(
            model_name='people',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='people',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='people',
            name='name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='people',
            name='password',
        ),
        migrations.RemoveField(
            model_name='people',
            name='token',
        ),
        migrations.AddField(
            model_name='people',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True,  on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            # preserve_default=True,
        ),
    ]
