# Generated by Django 2.2.5 on 2019-10-30 01:33

from django.db import migrations, models

def add_services(apps, schema_editor):

    Service = apps.get_model("StudentHousing", "Service")

    feeding = Service(name='Alimentación', description='')
    feeding.save()

    tv = Service(name='Cable TV', description='')
    tv.save()

    internet = Service(name='Internet', description='')
    internet.save()

    laundry = Service(name='Lavandería', description='')
    laundry.save()

    cleaning = Service(name='Limpieza', description='')
    cleaning.save()

    kitchen = Service(name='Cocina disponible', description='')
    kitchen.save()

    privateBathroom = Service(name='Baño privado', description='')
    privateBathroom.save()



class Migration(migrations.Migration):

    dependencies = [
        ('StudentHousing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_services),
    ]
