# Generated by Django 2.2.5 on 2019-11-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHousing', '0002_add_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencepublication',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
