# Generated by Django 2.2.5 on 2019-11-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHousing', '0003_residencepublication_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='publication',
        ),
        migrations.AddField(
            model_name='residencepublication',
            name='services',
            field=models.ManyToManyField(to='StudentHousing.Service'),
        ),
    ]
