# Generated by Django 2.2.5 on 2019-12-15 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHousing', '0005_auto_20191213_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='publication',
        ),
        migrations.AddField(
            model_name='residencepublication',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentHousing.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='locality',
            field=models.CharField(max_length=255),
        ),
    ]
